# site settings
title: Vipin Kumar
subtitle: Projects
email: vipin.ind.kumar@gmail.com
description: "Machine Learning:\ Deep Learning, Convolutional Neural Networks, Recurrent Neural Networks
             Languages:\ Python, Matlab/Octave, Java, C, JavaScript, PHP, SQL, Standard ML, Racket
             Technologies:\ Scikit-Learn, Keras, TensorFlow, pandas, NumPy, Linux
             Computer Science:\ Programming language theory, Functional Programming, OOP, Systematic Program Design"
baseurl: "/projects" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: Delhi
state: 
zip_code: 
country: India
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/VipinindKumar/
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/vipinindkumar/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
