# site settings
title: Vipin Kumar
subtitle: Projects
email: vipin.ind.kumar@gmail.com
description: "Machine Learning, Deep Learning, Feature Engineering, Computer Vision, Model Deployment, Data Mining and Cleaning,
              Version Control, Python, Scikit-Learn, Keras, TensorFlow, Pandas, NumPy, CNN, RNN, SQL, Probability, Statistics,
              NLP, Heroku, AWS, Matlab/Octave, Java, C, JavaScript, Apache Spark, OpenCV, XGBoost, Linux, Flask,
              Programming Language Theory, Functional Programming, Object Oriented Programming, Systematic Program Design"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: Delhi
state: 
zip_code: 
country: India
phone: ----------

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 9

# social settings
500px_url:
facebook_url:
github_url: https://github.com/VipinindKumar/
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/vipinindkumar/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
